### ISSUE TITLE
Cartpoleviz

### ISSUE THREAD

**Issue by ElliotWood** [microsoft/cartpole-py#10]
Hi 
Could I please have access to /Cartpoleviz/? Or a refence on how to roll our own?

Kind Regards,
Elliot Wood

**Comment by ForrestTrepte** [comment]
Hello @ElliotWood. SimulatorVisualizer is a built-in feature that is only supported for the simulation states of the Cartpole and Moab samples.

It is a great feature suggestion to support the ability to create custom visualizers for any simulation.

Currently I recommend creating a visualization that runs on your local PC during training. It is possible to register a local simulator will run at the same time as other simulators are running in the cloud. Alternatively, you could [enable logging and use episode logs](https://docs.microsoft.com/en-us/bonsai/guides/query-log-data) to create visualizations after the fact.

Would something like that meet your needs?

**Comment by ElliotWood** [comment]
Thanks for getting back to me so quickly @ForrestTrepte. Running the simulation locally with local sim offers what is achieved now with me team, id love to explore the in-browser experience further.

I took a little while to understand how it works and so far have determined the following:
- The IFrame loads a react application with Three js, the 'state' of this app sets the position, angle, etc of the OBJ loaded.
- a Window listener captures the data from the parent window via "on 'message' received", which receives its update from SignalR in realtime.
- The simulation UI sets the IFrame from the 'SimulatorVisualizer' variable in the config.

So with that context, 
I created a react app of my own with the same hook and state and model in THREE.js then,
set the SimulatorVisualizer ='http://<url>/customerviz' hoping it would load on and work as intended. 

However, it clears the value out (possibly because is not a local address?) and did not show the IFrame. I can get it working if i load the browser tooling and set the property manually, which does load the IFrame correctly. 

If this mechanism could be supported it would greatly improve the experience.

Kind Regards,
Elliot Wood

**Comment by ForrestTrepte** [comment]
Wow, @ElliotWood, it's impressive that you got that working! 😲 Could it be that 'http:///customerviz' is not a valid URL with the three slashes? I honestly don't know if this can be made to work smoothly. Or perhaps there could be a problem with nonlocal addresses. This feature is only officially supported for our built-in Cartpole and Moab samples. And I'm worried that at some point we may change it in a way that will break the approach you are using.

Thank you for the feedback that a supported version of custom visualization would be useful. Would you be willing to take a few minutes to talk with us about how you use Bonsai and to show us a demo of your prototype visualization? I can't promise that we'll support this feature, but we are actively considering it right now. @ElliotWood, if you would like to do that would it be OK if I connect with you via LinkedIn to work out the details?

**Comment by ElliotWood** [comment]
Thanks :) re:SimulatorVisualizer I found that there is a filter function that only accepts 3 sim vis `URLs`
<img width="1028" alt="Override" src="https://user-images.githubusercontent.com/1829224/126023511-c7250835-4095-4558-96c4-7667a934935d.png">

Here is it working, if I add http://localhost:3000 to the list of accepted urls. Once added it works great.
<img width="1920" alt="2021-07-17 (12)" src="https://user-images.githubusercontent.com/1829224/126023346-7dea1891-ae73-4b5b-8834-d98a648913c9.png">


The React App has a 'state' that is captured from the parent window as mentioned.
<img width="1920" alt="2021-07-17 (18)" src="https://user-images.githubusercontent.com/1829224/126023360-7b4086fd-e8c3-47fa-a124-b0456d2775fc.png">

A supported version would definitely be useful, I would also encourage openness with your design. It's ok if things change I think versioning your VisualiserInfo Module would be neat? 
Possibly 
```SimulatorVisualizer = "" -> SimulatorVisualizer = { url: "", version:"" }```

Would love to connect further on LinkedIn :) 
https://www.linkedin.com/in/elliot-wood-a2160347/

**Comment by ForrestTrepte** [comment]
Bonsai now supports creating custom simulator visualizers as described by [Tutorial: Connect your simulation visualization to Bonsai](https://docs.microsoft.com/en-us/bonsai/tutorials/visualizer-plugin).

Thanks for the suggestion, @ElliotWood! And when you have a chance to try it out please let us know if you have any feedback.
